runtime: python38
entrypoint: gunicorn -b :$PORT api:app

instance_class: F2

env_variables:
  GCP_PROJECT_ID: curanexa3

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 5

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
